### ISSUE TITLE
Documentation for Ubuntu/Debian

### ISSUE THREAD

**Issue by zevero** [AtmelUniversityFrance/atmel-samd21-xpro-boardmanagermodule#10]
Maybe you could include something about this error, when trying to flash

    Error: unable to open CMSIS-DAP device 0xd28:0x204

The USB is not registered correctly out of the box ... solution is either to run arduino as root, or follow
https://github.com/RedBearLab/nRF51822-Arduino/issues/73

**Comment by aethaniel** [comment]
Indeed, I will try to find a way to add this information somewhere:
>Linux udev rules:  arduino/OpenOCD/contrib/60-openocd.rules

>cd /etc/udev/rules.d
>sudo wget https://raw.githubusercontent.com/arduino/OpenOCD/master/contrib/60-openocd.rules
>sudo udevadm control --reload-rules
