### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by alexptbg** [AtmelUniversityFrance/atmel-samd21-xpro-boardmanagermodule#5]
I am developing arduino based micro controllers for about 4 years.

Recently i bayed some SAMD21J18 processors and the atmel samd21 xpro to test it.

I have the Atmel samd21 xpro kit, had success with the upload part but eventually the pins are not the same in the output as they are defined in the pins_arduino, because i have no success with the blink example.

I tried some different output pins (PB04,PB05,PB06,PB07,PA27,PA28,PA30) and no success, even the serial.print doesn't print anything. Also tried as normal arduino digital pins, for example: instead of using digital write PB04 also tried digital write 6 (digital pin 6) and PORT_ / PORTA / PORTB, etc...   

I believe that there is some issue in the pin definitions.

Can some one help me here?

Thanks in advance, 

Alex Soares

**Comment by aethaniel** [comment]
Hi @alexptbg, your confusion may come from missing documentation in the wiki regarding the pinmap used for each boards.
You can find it in file https://github.com/AtmelUniversityFrance/atmel-samd21-xpro-boardmanagermodule/blob/master/module/variants/atmel_samd21_xpro_v1/variant.cpp. The pin number in first column is the index to be used for example with digitalWrite() and similar functions expecting a pin number.

**Comment by aethaniel** [comment]
wiki https://github.com/AtmelUniversityFrance/atmel-samd21-xpro-boardmanagermodule/wiki updated to bring more information.
