### ISSUE TITLE
ATSAMW25 missing bootloader

### ISSUE THREAD

**Issue by theOzzieRat** [AtmelUniversityFrance/atmel-samd21-xpro-boardmanagermodule#6]
When you try and burn the bootloader to a ATSAMW25 the bootloader file cannot be found.  The directory it looks for the bootloader in only contains a Makefile.

**Comment by joostd** [comment]
I managed to work around this issue by using the SAMD21 bootloader:

`cd Library/Arduino15/packages/atmel-samd21-xpros/hardware/samd/0.2.0/bootloaders/`

`cp atmel_samd21_xpro_v1/samd21_sam_ba.bin atmel_samw25_xpro/`

**Comment by aethaniel** [comment]
@theOzzieRat @joostd, indeed SAMW25 being a D21, using the same bootloader is the solution.
I will update this 'detail' for coming v0.3.0.

**Comment by aethaniel** [comment]
fixed by https://github.com/AtmelUniversityFrance/atmel-samd21-xpro-boardmanagermodule/commit/a1c40ac09f0a885dac4ae1e741fb4b088169fb24
