### ISSUE TITLE
ATSAMW25 wifi does not work

### ISSUE THREAD

**Issue by theOzzieRat** [AtmelUniversityFrance/atmel-samd21-xpro-boardmanagermodule#7]
The variant.h for the ATSAMW25 is incorrect for the Wifi module.  I have got it working after editing the variant.h file (attached).
[variant.h.txt](https://github.com/AtmelUniversityFrance/atmel-samd21-xpro-boardmanagermodule/files/560235/variant.h.txt)

**Comment by joostd** [comment]
Doesn't seem to make any difference with my SAMW25 Xplained Pro board.

**Comment by aethaniel** [comment]
thanks @theOzzieRat, I will take a look. sorry being late on this, I never received any notifications :'(

**Comment by aethaniel** [comment]
integrated via https://github.com/AtmelUniversityFrance/atmel-samd21-xpro-boardmanagermodule/commit/07a1eed232f1e16b3895272f72d5aca1a3e06027
